-- ============================================================================
-- Migration 012: meals por serviço de refeição
-- Criada em: 2026-03-22
-- Proposito:
--   - introduzir catalogo de serviços de refeição por evento
--   - impedir repetição da mesma refeição no mesmo dia
--   - registrar custo aplicado e idempotência offline por baixa
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.event_meal_services (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL,
    service_code character varying(50) NOT NULL,
    label character varying(120) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    starts_at time without time zone,
    ends_at time without time zone,
    unit_cost numeric(10,2) NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.event_meal_services
    ADD CONSTRAINT event_meal_services_event_fk
    FOREIGN KEY (event_id)
    REFERENCES public.events(id)
    ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_event_meal_services_code
    ON public.event_meal_services (event_id, service_code);

CREATE INDEX IF NOT EXISTS idx_event_meal_services_order
    ON public.event_meal_services (event_id, sort_order);

ALTER TABLE public.participant_meals
    ADD COLUMN IF NOT EXISTS meal_service_id integer,
    ADD COLUMN IF NOT EXISTS unit_cost_applied numeric(10,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS offline_request_id character varying(120);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.participant_meals'::regclass
          AND conname = 'fk_pm_meal_service'
    ) THEN
        ALTER TABLE public.participant_meals
            ADD CONSTRAINT fk_pm_meal_service
            FOREIGN KEY (meal_service_id)
            REFERENCES public.event_meal_services(id)
            ON DELETE SET NULL
            NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_participant_meals_meal_service
    ON public.participant_meals (meal_service_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_participant_meals_service_once_per_day
    ON public.participant_meals (participant_id, event_day_id, meal_service_id)
    WHERE meal_service_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_participant_meals_offline_request
    ON public.participant_meals (offline_request_id)
    WHERE offline_request_id IS NOT NULL;

DO $$
BEGIN
    UPDATE public.participant_meals pm
    SET unit_cost_applied = COALESCE(pm.unit_cost_applied, ofs.meal_unit_cost, 0)
    FROM public.event_participants ep
    JOIN public.events e ON e.id = ep.event_id
    LEFT JOIN LATERAL (
        SELECT COALESCE(ofs.meal_unit_cost, 0) AS meal_unit_cost
        FROM public.organizer_financial_settings ofs
        WHERE ofs.organizer_id = e.organizer_id
        ORDER BY ofs.id DESC
        LIMIT 1
    ) ofs ON TRUE
    WHERE ep.id = pm.participant_id
      AND COALESCE(pm.unit_cost_applied, 0) = 0;
EXCEPTION
    WHEN undefined_column THEN
        RAISE NOTICE 'Backfill de unit_cost_applied pulado: organizer_financial_settings.meal_unit_cost indisponivel.';
END $$;

DO $$
DECLARE
    duplicate_service_rows integer;
    missing_meal_service_rows integer;
BEGIN
    SELECT COUNT(*)
    INTO duplicate_service_rows
    FROM (
        SELECT participant_id, event_day_id, meal_service_id
        FROM public.participant_meals
        WHERE meal_service_id IS NOT NULL
        GROUP BY participant_id, event_day_id, meal_service_id
        HAVING COUNT(*) > 1
    ) duplicates;

    SELECT COUNT(*)
    INTO missing_meal_service_rows
    FROM public.participant_meals pm
    WHERE pm.meal_service_id IS NOT NULL
      AND NOT EXISTS (
          SELECT 1
          FROM public.event_meal_services ems
          WHERE ems.id = pm.meal_service_id
      );

    IF duplicate_service_rows = 0 AND missing_meal_service_rows = 0 THEN
        ALTER TABLE public.participant_meals VALIDATE CONSTRAINT fk_pm_meal_service;
    ELSE
        RAISE NOTICE 'fk_pm_meal_service mantida NOT VALID: % duplicidade(s) e % serviço(s) inexistente(s).', duplicate_service_rows, missing_meal_service_rows;
    END IF;
END $$;

COMMIT;
