-- ============================================================================
-- Migration 017: participant_meals outside operational day quarantine
-- Criada em: 2026-03-23
-- Proposito:
--   - colocar em quarentena os 8 registros legados que ficaram fora de qualquer
--     janela operacional valida de event_days no evento 7
--   - preservar snapshot completo para reversao
--   - registrar trilha em audit_log
-- Importante:
--   - migration intencionalmente conservadora e travada nos IDs auditados
--   - nao aplicar sem confirmacao explicita
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.participant_meals_quarantine (
    quarantine_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_meal_id integer NOT NULL UNIQUE,
    participant_id integer NOT NULL,
    event_day_id integer NOT NULL,
    event_shift_id integer,
    consumed_at timestamp without time zone,
    meal_service_id integer,
    unit_cost_applied numeric(12,2),
    offline_request_id character varying(100),
    quarantined_at timestamp with time zone DEFAULT now() NOT NULL,
    quarantine_batch character varying(64) NOT NULL,
    quarantine_reason text NOT NULL,
    source_issue_class character varying(64) NOT NULL,
    source_event_id integer NOT NULL,
    source_event_name character varying(255),
    source_organizer_id integer,
    source_event_day_date date,
    source_day_starts_at timestamp without time zone,
    source_day_ends_at timestamp without time zone,
    matched_day_count integer DEFAULT 0 NOT NULL,
    matched_event_day_id integer,
    matched_event_day_ids text,
    source_snapshot jsonb NOT NULL,
    diagnostic_snapshot jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pm_quarantine_batch
    ON public.participant_meals_quarantine (quarantine_batch, quarantined_at DESC);

CREATE INDEX IF NOT EXISTS idx_pm_quarantine_event
    ON public.participant_meals_quarantine (source_event_id, source_event_day_date);

CREATE TEMP TABLE tmp_participant_meals_quarantine_candidates ON COMMIT DROP AS
WITH expected_ids(id) AS (
    VALUES (1), (2), (3), (4), (5), (6), (7), (8)
),
meal_scope AS (
    SELECT
        pm.id AS participant_meal_id,
        pm.participant_id,
        pm.event_day_id,
        pm.event_shift_id,
        pm.consumed_at,
        pm.meal_service_id,
        pm.unit_cost_applied,
        pm.offline_request_id,
        ep.event_id,
        e.name AS event_name,
        e.organizer_id,
        ed.date AS event_day_date,
        ed.starts_at AS day_starts_at,
        ed.ends_at AS day_ends_at,
        ems.service_code AS meal_service_code,
        to_jsonb(pm) AS source_snapshot
    FROM public.participant_meals pm
    JOIN expected_ids ei ON ei.id = pm.id
    JOIN public.event_participants ep ON ep.id = pm.participant_id
    JOIN public.event_days ed ON ed.id = pm.event_day_id
    JOIN public.events e ON e.id = ed.event_id
    LEFT JOIN public.event_meal_services ems ON ems.id = pm.meal_service_id
    WHERE ep.event_id = ed.event_id
),
matched_days AS (
    SELECT
        ms.participant_meal_id,
        COUNT(ed_match.id)::int AS matched_day_count,
        MIN(ed_match.id) AS matched_event_day_id,
        STRING_AGG(
            ed_match.id::text,
            ',' ORDER BY COALESCE(ed_match.starts_at, ed_match.date::timestamp), ed_match.id
        ) AS matched_event_day_ids
    FROM meal_scope ms
    LEFT JOIN public.event_days ed_match
           ON ed_match.event_id = ms.event_id
          AND ms.consumed_at IS NOT NULL
          AND (
                (ed_match.starts_at IS NOT NULL AND ed_match.ends_at IS NOT NULL AND ms.consumed_at >= ed_match.starts_at AND ms.consumed_at <= ed_match.ends_at)
                OR ((ed_match.starts_at IS NULL OR ed_match.ends_at IS NULL) AND ms.consumed_at::date = ed_match.date)
          )
    GROUP BY ms.participant_meal_id
),
classified AS (
    SELECT
        ms.*,
        COALESCE(md.matched_day_count, 0) AS matched_day_count,
        md.matched_event_day_id,
        md.matched_event_day_ids,
        CASE
            WHEN ms.consumed_at IS NULL THEN 'missing_consumed_at'
            WHEN COALESCE(md.matched_day_count, 0) = 0 THEN 'no_operational_day_match'
            WHEN COALESCE(md.matched_day_count, 0) > 1 THEN 'ambiguous_operational_day_match'
            WHEN md.matched_event_day_id <> ms.event_day_id THEN 'wrong_event_day_reference'
            ELSE 'ok'
        END AS source_issue_class
    FROM meal_scope ms
    LEFT JOIN matched_days md ON md.participant_meal_id = ms.participant_meal_id
)
SELECT
    participant_meal_id,
    participant_id,
    event_day_id,
    event_shift_id,
    consumed_at,
    meal_service_id,
    unit_cost_applied,
    offline_request_id,
    event_id AS source_event_id,
    event_name AS source_event_name,
    organizer_id AS source_organizer_id,
    event_day_date AS source_event_day_date,
    day_starts_at AS source_day_starts_at,
    day_ends_at AS source_day_ends_at,
    matched_day_count,
    matched_event_day_id,
    matched_event_day_ids,
    source_issue_class,
    source_snapshot,
    jsonb_build_object(
        'event_name', event_name,
        'meal_service_code', meal_service_code,
        'current_event_day_id', event_day_id,
        'current_event_day_date', event_day_date,
        'current_day_starts_at', day_starts_at,
        'current_day_ends_at', day_ends_at,
        'matched_day_count', matched_day_count,
        'matched_event_day_id', matched_event_day_id,
        'matched_event_day_ids', matched_event_day_ids
    ) AS diagnostic_snapshot
FROM classified
WHERE source_issue_class = 'no_operational_day_match';

DO $$
DECLARE
    expected_count integer := 8;
    candidate_count integer := 0;
    duplicate_count integer := 0;
    linked_count integer := 0;
    unexpected_event_count integer := 0;
BEGIN
    SELECT COUNT(*) INTO candidate_count
    FROM tmp_participant_meals_quarantine_candidates;

    IF candidate_count <> expected_count THEN
        RAISE EXCEPTION
            'Quarentena 017 abortada: esperados % registros candidatos, encontrados %.',
            expected_count,
            candidate_count;
    END IF;

    SELECT COUNT(*) INTO duplicate_count
    FROM public.participant_meals_quarantine pq
    JOIN tmp_participant_meals_quarantine_candidates tmp
      ON tmp.participant_meal_id = pq.participant_meal_id;

    IF duplicate_count > 0 THEN
        RAISE EXCEPTION
            'Quarentena 017 abortada: % registro(s) ja estao em participant_meals_quarantine.',
            duplicate_count;
    END IF;

    SELECT COUNT(*) INTO linked_count
    FROM tmp_participant_meals_quarantine_candidates
    WHERE meal_service_id IS NOT NULL
       OR event_shift_id IS NOT NULL;

    IF linked_count > 0 THEN
        RAISE EXCEPTION
            'Quarentena 017 abortada: ha % registro(s) com meal_service_id/event_shift_id preenchidos.',
            linked_count;
    END IF;

    SELECT COUNT(*) INTO unexpected_event_count
    FROM tmp_participant_meals_quarantine_candidates
    WHERE source_event_id <> 7
       OR event_day_id <> 13;

    IF unexpected_event_count > 0 THEN
        RAISE EXCEPTION
            'Quarentena 017 abortada: ha % registro(s) fora do recorte auditado do evento 7 / event_day_id 13.',
            unexpected_event_count;
    END IF;
END $$;

INSERT INTO public.participant_meals_quarantine (
    participant_meal_id,
    participant_id,
    event_day_id,
    event_shift_id,
    consumed_at,
    meal_service_id,
    unit_cost_applied,
    offline_request_id,
    quarantined_at,
    quarantine_batch,
    quarantine_reason,
    source_issue_class,
    source_event_id,
    source_event_name,
    source_organizer_id,
    source_event_day_date,
    source_day_starts_at,
    source_day_ends_at,
    matched_day_count,
    matched_event_day_id,
    matched_event_day_ids,
    source_snapshot,
    diagnostic_snapshot
)
SELECT
    participant_meal_id,
    participant_id,
    event_day_id,
    event_shift_id,
    consumed_at,
    meal_service_id,
    unit_cost_applied,
    offline_request_id,
    now(),
    '017_outside_operational_day_quarantine',
    'Legacy meal outside any configured operational day window.',
    source_issue_class,
    source_event_id,
    source_event_name,
    source_organizer_id,
    source_event_day_date,
    source_day_starts_at,
    source_day_ends_at,
    matched_day_count,
    matched_event_day_id,
    matched_event_day_ids,
    source_snapshot,
    diagnostic_snapshot
FROM tmp_participant_meals_quarantine_candidates
ORDER BY participant_meal_id ASC;

INSERT INTO public.audit_log (
    occurred_at,
    user_email,
    session_id,
    action,
    entity_type,
    entity_id,
    previous_value,
    new_value,
    event_id,
    metadata,
    result,
    organizer_id
)
SELECT
    now(),
    'migration:017',
    'migration:017',
    'meal.quarantine_legacy',
    'participant_meals_batch',
    '017_outside_operational_day_quarantine',
    NULL,
    NULL,
    MIN(source_event_id),
    jsonb_build_object(
        'batch', '017_outside_operational_day_quarantine',
        'reason', 'Legacy meals outside any configured operational day window.',
        'rows_total', COUNT(*),
        'participant_meal_ids', jsonb_agg(participant_meal_id ORDER BY participant_meal_id),
        'review_source', '016_participant_meals_outside_operational_day_review.sql'
    ),
    'success',
    MIN(source_organizer_id)
FROM tmp_participant_meals_quarantine_candidates;

WITH deleted AS (
    DELETE FROM public.participant_meals pm
    USING tmp_participant_meals_quarantine_candidates tmp
    WHERE pm.id = tmp.participant_meal_id
    RETURNING pm.id
)
SELECT COUNT(*) AS rows_quarantined
FROM deleted;

COMMIT;

-- Reversao manual sugerida:
--   1. reinserir a linha original em participant_meals a partir de source_snapshot
--   2. remover a linha correspondente em participant_meals_quarantine
-- Exemplo base:
-- INSERT INTO public.participant_meals (
--     id, participant_id, event_day_id, event_shift_id, consumed_at,
--     meal_service_id, unit_cost_applied, offline_request_id
-- )
-- SELECT
--     participant_meal_id,
--     participant_id,
--     event_day_id,
--     event_shift_id,
--     consumed_at,
--     meal_service_id,
--     unit_cost_applied,
--     offline_request_id
-- FROM public.participant_meals_quarantine
-- WHERE quarantine_batch = '017_outside_operational_day_quarantine'
-- ORDER BY participant_meal_id ASC;
