BEGIN;

ALTER TABLE IF EXISTS public.event_card_assignments
    ADD COLUMN IF NOT EXISTS participant_id integer,
    ADD COLUMN IF NOT EXISTS person_id integer,
    ADD COLUMN IF NOT EXISTS sector character varying(50),
    ADD COLUMN IF NOT EXISTS source_module character varying(50),
    ADD COLUMN IF NOT EXISTS source_batch_id bigint,
    ADD COLUMN IF NOT EXISTS source_role_id integer,
    ADD COLUMN IF NOT EXISTS source_event_role_id integer,
    ADD COLUMN IF NOT EXISTS issued_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS notes text;

UPDATE public.event_card_assignments
SET issued_at = COALESCE(issued_at, created_at, CURRENT_TIMESTAMP)
WHERE issued_at IS NULL;

CREATE TABLE IF NOT EXISTS public.card_issue_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id integer NOT NULL,
    event_id integer NOT NULL,
    source_module character varying(50) NOT NULL,
    source_context jsonb,
    requested_count integer DEFAULT 0 NOT NULL,
    preview_eligible_count integer DEFAULT 0 NOT NULL,
    issued_count integer DEFAULT 0 NOT NULL,
    skipped_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    created_by_user_id integer,
    idempotency_key character varying(120),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.card_issue_batch_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id bigint NOT NULL,
    participant_id integer,
    person_id integer,
    existing_card_id uuid,
    issued_card_id uuid,
    status character varying(20) NOT NULL,
    reason_code character varying(80),
    reason_message text,
    sector character varying(50),
    source_role_id integer,
    source_event_role_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_event_card_assignments_participant'
          AND conrelid = 'public.event_card_assignments'::regclass
    ) THEN
        ALTER TABLE public.event_card_assignments
            ADD CONSTRAINT fk_event_card_assignments_participant
            FOREIGN KEY (participant_id) REFERENCES public.event_participants(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_event_card_assignments_person'
          AND conrelid = 'public.event_card_assignments'::regclass
    ) THEN
        ALTER TABLE public.event_card_assignments
            ADD CONSTRAINT fk_event_card_assignments_person
            FOREIGN KEY (person_id) REFERENCES public.people(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_event_card_assignments_batch'
          AND conrelid = 'public.event_card_assignments'::regclass
    ) THEN
        ALTER TABLE public.event_card_assignments
            ADD CONSTRAINT fk_event_card_assignments_batch
            FOREIGN KEY (source_batch_id) REFERENCES public.card_issue_batches(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_event_card_assignments_role'
          AND conrelid = 'public.event_card_assignments'::regclass
    ) THEN
        ALTER TABLE public.event_card_assignments
            ADD CONSTRAINT fk_event_card_assignments_role
            FOREIGN KEY (source_role_id) REFERENCES public.workforce_roles(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_event_card_assignments_event_role'
          AND conrelid = 'public.event_card_assignments'::regclass
    ) THEN
        ALTER TABLE public.event_card_assignments
            ADD CONSTRAINT fk_event_card_assignments_event_role
            FOREIGN KEY (source_event_role_id) REFERENCES public.workforce_event_roles(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batches_event'
          AND conrelid = 'public.card_issue_batches'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batches
            ADD CONSTRAINT fk_card_issue_batches_event
            FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batches_created_by'
          AND conrelid = 'public.card_issue_batches'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batches
            ADD CONSTRAINT fk_card_issue_batches_created_by
            FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_card_issue_batch_items_status'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT chk_card_issue_batch_items_status
            CHECK (status IN ('issued', 'skipped', 'failed')) NOT VALID;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_batch'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_batch
            FOREIGN KEY (batch_id) REFERENCES public.card_issue_batches(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_participant'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_participant
            FOREIGN KEY (participant_id) REFERENCES public.event_participants(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_person'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_person
            FOREIGN KEY (person_id) REFERENCES public.people(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_existing_card'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_existing_card
            FOREIGN KEY (existing_card_id) REFERENCES public.digital_cards(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_issued_card'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_issued_card
            FOREIGN KEY (issued_card_id) REFERENCES public.digital_cards(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_role'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_role
            FOREIGN KEY (source_role_id) REFERENCES public.workforce_roles(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_card_issue_batch_items_event_role'
          AND conrelid = 'public.card_issue_batch_items'::regclass
    ) THEN
        ALTER TABLE public.card_issue_batch_items
            ADD CONSTRAINT fk_card_issue_batch_items_event_role
            FOREIGN KEY (source_event_role_id) REFERENCES public.workforce_event_roles(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_event_card_assignments_participant_event_status
    ON public.event_card_assignments USING btree (participant_id, event_id, status);

CREATE INDEX IF NOT EXISTS idx_event_card_assignments_person_event_status
    ON public.event_card_assignments USING btree (person_id, event_id, status);

CREATE INDEX IF NOT EXISTS idx_event_card_assignments_source_batch
    ON public.event_card_assignments USING btree (source_batch_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_event_card_assignments_active_participant_event
    ON public.event_card_assignments USING btree (event_id, participant_id)
    WHERE ((status)::text = 'active'::text AND participant_id IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_card_issue_batches_event_created_at
    ON public.card_issue_batches USING btree (organizer_id, event_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_card_issue_batches_scope_idempotency
    ON public.card_issue_batches USING btree (organizer_id, event_id, source_module, idempotency_key)
    WHERE (NULLIF(BTRIM(COALESCE(idempotency_key, '')), '') IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_card_issue_batch_items_batch_status
    ON public.card_issue_batch_items USING btree (batch_id, status);

CREATE INDEX IF NOT EXISTS idx_card_issue_batch_items_participant
    ON public.card_issue_batch_items USING btree (participant_id);

COMMIT;
